### ISSUE TITLE
Access from other activity

### ISSUE THREAD

**Issue by mkiisoft** [tozny/java-aes-crypto#17]
Hello guys! I've a problem... what if I want to decrypt the string from other activity/fragment/etc?

As far as I can see, I need the CipherTextIvMac and keys, the same ones used for encrypt. Wouldn't be a best option to set a key value, pass it and the encrypted string for decrypt?

That way we can move around the data and keep it safe/secure.

**Comment by SyntaxPolice** [comment]
To decrypt the data (CipherTextIvMac), you need the decryption keys. AES is a symmetric algorithm, so the same keys used for decryption are also used for encryption.

There is already a function to pass the key value and the encrypted strings for decrypt.

Can you clarify your request, please?

**Comment by mkiisoft** [comment]
Let's just say I've generate my key and I've encrypted my string. Now, that string I've storage on a SharedPreference (keep encrypted and can be move around anywhere any time)... when I return the Shared would be just a string encrypted from another Activity, any other way where I didn't generate the keys and encrypted the string. Maybe the sample didn't get me a clear idea... but key are not generated random? how to get the same key value from other place? and the CipherTextIvMac? Maybe an example of how to do it would be great.

**Comment by SyntaxPolice** [comment]
Hi mkiisoft,

You do indeed need the key to decrypt the ciphertext, so if you are at a part of the code where that key is not available, you have to find a way to share or generate the same key. That's just how symmetric crypto works.

There are two ways to generate keys in our library:
1. Randomly
2. Based on passwords

If you use method 1, you definitely will need to store the key somewhere. Sadly there aren't too  many good options for that on Android.

For 2, you can re-generate the same key with the same password every time; just use the obviously-named function.
