### ISSUE TITLE
MAC stores in civ does not match computed MAC

### ISSUE THREAD

**Issue by LeHaine** [tozny/java-aes-crypto#19]
Hello guys! Thanks for the awesome library. I am running into an issue with decrypting a string that is stored in Preferences. 

So what I am doing is generating a key based on a password and storing the salt. I regenerate the key whenever I need access to it. What I am trying to do those is decrypt the encrypted string without the CiperTextIvMac available.

So an example:

I get plain text -> encrypt it -> store on shared preferences.
Open app up a later time after it has been completely closed -> retrieve encrypted string from preferences -> decrypt string -> get plain text.

But what happens when I try to decrypt is
```
java.security.GeneralSecurityException: MAC stored in civ does not match computed MAC.
10-21 10:54:40.084  15146-15146/app_android W/System.err﹕ at app_android.security.AesCbcWithIntegrity.decrypt(AesCbcWithIntegrity.java:368)
10-21 10:54:40.084  15146-15146/app_android W/System.err﹕ at app_android.security.AesCbcWithIntegrity.decryptString(AesCbcWithIntegrity.java:331)
10-21 10:54:40.084  15146-15146/app_android W/System.err﹕ at app_android.security.AesCbcWithIntegrity.decryptString(AesCbcWithIntegrity.java:346)
```
Here is my code to decrypt:
```
String salt = getSalt();
AesCbcWithIntegrity.SecretKeys keys =   AesCbcWithIntegrity.generateKeyFromPassword(Constants.KEY, salt);
decryptedUsername = AesCbcWithIntegrity.decryptString(new   AesCbcWithIntegrity.CipherTextIvMac(username), keys);
```

Not sure if I am missing something obvious. But thanks for the help.

**Comment by LeHaine** [comment]
And tried with this code just to see if it works and receiving the same error:

                    String salt = getSalt();
                    AesCbcWithIntegrity.SecretKeys keys = AesCbcWithIntegrity.generateKeyFromPassword(Constants.KEY, salt);
                    AesCbcWithIntegrity.CipherTextIvMac ctim = new AesCbcWithIntegrity.CipherTextIvMac(username.getBytes(), AesCbcWithIntegrity.generateIv(), AesCbcWithIntegrity.generateMac(username.getBytes(), keys.getIntegrityKey()));
                    decryptedUsername = AesCbcWithIntegrity.decryptString(ctim, keys);

**Comment by LeHaine** [comment]
It seems to be the the result in the constantTimeEq method is returning a -1 instead of 0.

**Comment by LeHaine** [comment]
Wow nevermind I am dumb. I though I added in the code to store the salt but I did not. EVERYTHING WORKS AS IT SHOULD.

**Comment by SyntaxPolice** [comment]
Ha! Thanks for working through the problem. I'm glad you got it working.

Can you share any information about what you're using the library for? We
are always interested in how are users use it.

peace,

  Isaac, sent from a mobile device

**Comment by LeHaine** [comment]
Hola!
 I am using it to store username and password so user can be signed in automatically instead of typing every time. I do not know much about encryption but your library is very awesome!

Saludos
Colt

**Comment by SyntaxPolice** [comment]
Thanks!

peace,

  Isaac, sent from a mobile device
