### ISSUE TITLE
can I pass my own custom seed for encryption?

### ISSUE THREAD

**Issue by MangeshKadam** [tozny/java-aes-crypto#23]

**Comment by SyntaxPolice** [comment]
Not sure what you mean about seeding for encryption. Key generation? Seeding the RNG?

There is no built in functionality to seed SecureRandom with your own value, but look at the [PRNG fix](https://github.com/tozny/java-aes-crypto/blob/master/aes-crypto/src/main/java/com/tozny/crypto/android/AesCbcWithIntegrity.java#L606) and related functions like [generate seed](https://github.com/tozny/java-aes-crypto/blob/master/aes-crypto/src/main/java/com/tozny/crypto/android/AesCbcWithIntegrity.java#L891).

You can modify these functions accordingly. If you have your own source of random number generation, about half the code in the library is unnecessary.
