### ISSUE TITLE
Where to store the generated key? 

### ISSUE THREAD

**Issue by strider29** [tozny/java-aes-crypto#25]
Once the key is generated where should I store it?

**Comment by SyntaxPolice** [comment]
You can convert the keys to a string using the included functions and
store them
however you like. Eg in preferences, keychain, or SQL.

Alternately, depending on your application, it's possibly more secure to
use keys that are generated from a password the user enters, and regenerate
it each time.

For more info on 4.3 and later:
http://developer.android.com/training/articles/keystore.html

**Comment by joaolisboa** [comment]
@SyntaxPolice 
How can I re-generate a key with a password inserted by the user with the randomized salt? I'm trying this out but it's giving me an error saying that "MAC stored in civ does not match computed MAC." Or is it another issue?

**Comment by SyntaxPolice** [comment]
To generate the same key from the same passphrase, you need to use the same
salt each time. The generate salt function provided is to be used only when
generating it the first time. Subsequently, you should use the same value.
For instance, you can store it somewhere.

peace,

  isaac

**Comment by joaolisboa** [comment]
Ok. Thanks!

**Comment by PunchyRascal** [comment]
What about storing the keys in AndroidKeyStore, which seems to support only private keys and certificates?
(https://github.com/tozny/java-aes-crypto/issues/43)

**Comment by SyntaxPolice** [comment]
You raise a good point about AKS, which has gotten pretty nice over the last few releases, and my response from February 2016 links to AKS. We have tentative plans to integrate this library more seamlessly with AKS. It's a great choice at this point on newer Android phones.

However, if you're going to store the key, there's no reason to derive it from the password. The whole point of password-derived keys is so you don't have to support them. So it just depends on what you're going for. I'll chime in on #43 as well.
