### ISSUE TITLE
Allow some params to be editable

### ISSUE THREAD

**Issue by skippy** [tozny/java-aes-crypto#27]
I'm thinking of specifically `AES_KEY_LENGTH_BITS` and  `PBE_ITERATION_COUNT`; we would like to set these to 256 and 20_000 respectively.  Of course we can just copy/paste the file into our build, but it would be nice to be able to import it in directly.

**Comment by SyntaxPolice** [comment]
Thanks. We want to keep this code pretty simple and always compatible (modifying key lenghts and iteration counts make different versions incompatible). Our TozStore libraries are a lot more feature rich, and we may provide an updated version of this library at some point that would be restricted to more modern phones (bigger key sizes, more cpu for iterations, gcm cipher, etc).

**Comment by SyntaxPolice** [comment]
And sorry for not replying earlier.
