### ISSUE TITLE
Support for GCM chiper transformation

### ISSUE THREAD

**Issue by duddu** [tozny/java-aes-crypto#33]
While using this class, if Android <4.4 is not on plate, would it be a legit (and sensible) choice to replace `AES/CBC/PKCS5Padding` with `AES/GCM/NoPadding`? Is it a redundant option, due to the integrity checking you added?
If it makes sense, are there other changes required in order to optimize the class, aside from reducing the IV length to 12 bytes?
Any suggestion is welcome
Thanks

**Comment by SyntaxPolice** [comment]
Yes, that's legitimate and sensible.

You will likely want to change a lot:

- Many of the crypto RNG "fix" functions will also be redundant
- You also wouldn't need the verification hash since GCM already supports
verification. In short, if you're not worried about compatibility, your can
eliminate most of the code.

- Some parameters to GCM mode may be different because it can include
non-encrypted but verified data as well.

- Be aware that GCM has rather catastrophic consequences if you reuse the
IV, so be careful about generating unique ones.

- you might get surprised about what platforms have what cipher suites at
what strength. Be sure to test every platform of interest.

**Comment by duddu** [comment]
Ok all clear, thanks a lot for the explanation!

**Comment by SyntaxPolice** [comment]
No problem!

**Comment by diyfr** [comment]
News...
Electronic Codebook (ECB) mode: Under a given key, any given plaintext block always gets encrypted to the same ciphertext block. Thus, it does not hide data patterns well. In some senses, it doesn't provide serious message confidentiality, and it is not recommended for use in cryptographic protocols at all.
Cipher Block Chaining (CBC) with PKCS#5 padding (or PKCS#7) is susceptible to padding oracle attacks.
In both cases, Galois/Counter Mode (GCM) with no padding should be preferred.

This rule raises an issue when a Cipher instance is created with either ECB or CBC/PKCS5Padding mode.

[find-sec-bugs](https://find-sec-bugs.github.io/bugs.htm#PADDING_ORACLE)

**Comment by SyntaxPolice** [comment]
@diyfr , Thanks for the note. Have you evaluated our library as to whether it is vulnerable to the attacks you mention?

This library does not use ECB mode at all.

We do use CBC mode for backward compatibility; GCM is not available on all Android platforms, and a significant number of users are still on platforms where CBC is the best available cipher (see below).

With regard to padding oracle; We add MAC integrity checking before decryption. Further, this is primarily a local/password-derived function (ie what's the oracle?).

So I'm not clear how padding oracle could be accomplished here, although I could definitely be wrong about that! Do you have any specific insights?

For reference, I believe [GCM was added in API level 22](https://developer.android.com/guide/topics/security/cryptography) / Android 5.1, and here's the [current distribution adoption rates](https://venturebeat.com/2019/05/07/google-finally-updates-android-distribution-dashboard-pie-passes-10/):

- Android 9.0 Pie (August 2018): 10.4%
- Android 8.0/8.1 Oreo (August 2017, December 2017): Up 6.8 points to 28.3%
- Android 7.0/7.1 Nougat (August 2016, October 2016): Down 9.9 points 19.2%
- Android 6.0 Marshmallow (October 2015): Down 4.4 points to 16.9%
- Android 5.0/5.1 Lollipop (November 2014, March 2015): Down 3.4 points to 14.5%
- Android 4.4 KitKat (October 2013): Down 0.7 points to 6.9%
- Android 4.1/4.2/4.3 Jelly Bean (July 2012, November 2012, and July 2013): Down 1.8 points to 3.0%
- Android 4.0 Ice Cream Sandwich (December 2011): Flat at 0.3%
- Android 2.3 Gingerbread (December 2010): Up 0.1 points to 0.3%
