### ISSUE TITLE
aes-crypto missing from Maven Central

### ISSUE THREAD

**Issue by androidfu** [tozny/java-aes-crypto#34]
Added mavenCentral() to the build.gradle file and added the dependency to app/build.gradle, but aes-crypto is not available.  Tried "0.0.1", "0.+", and "1.+" (to match your most recent release).

**Comment by brandall76** [comment]
I'm having the same issue

**Comment by nilsi** [comment]
Yes same for me.

**Comment by yyysl** [comment]
how to see the recent release？

**Comment by pbochenski** [comment]
Until this issue is solved I've created jitpack build here: (https://jitpack.io/#pbochenski/java-aes-crypto/v1.1)

**Comment by jamesjb** [comment]
I've released version 1.1.0 of this library that includes Jitpack-hosted Maven installation instructions. See the updated README for the details.
