### ISSUE TITLE
Where should I store the salt?

### ISSUE THREAD

**Issue by nilsi** [tozny/java-aes-crypto#37]
Hello, thanks for a great library!

Im encrypting some data using an autogenerated password stored (for each user) on a server.
When I want to decrypt the data I then recreate the key with salt generated from java-aes-crypto. I am currently storing the salt in the SharedPreferences on the cellphone but this seems wrong since a potential hacker could easily access it if the phone is rooted.

Where should I store the salt?

**Comment by SyntaxPolice** [comment]
The salt is not secret, so you can store it next to the ciphertext. SharedPreferences is probably fine. The purpose of the salt is to make certain types of brute-force attacks difficult. The key / password is really the secret part.
