### ISSUE TITLE
Encrypted Stream...

### ISSUE THREAD

**Issue by spyhunter99** [tozny/java-aes-crypto#38]
Are there any examples for using this class to encrypt/decrypt a byte stream?

**Comment by hayribakici** [comment]
@spyhunter99 Hi,

I just discovered this library and I found a way to encrypt a byte Stream.
Here is the code:

`val buffer = "Hello World".toByteArray()
 // key = generateKey() like in the example
 val cipherTextIvMac = AesCbcWithIntegrity.encrypt(buffer, key)
 val cipheredString = cipherTextIvMac.toString()`

Unfortunately I wasn't manage to decrypt the string content as a _stream_. This is kind of missing. But it would be nice to have this feature.

**Comment by SyntaxPolice** [comment]
Sorry I never replied to this earlier. We try to keep this library relatively simple. The built-in encryption libraries in Java / Android do allow for stream encryption because of its chunked nature. Best of luck.
