### ISSUE TITLE
Caller-provided IV not permitted

### ISSUE THREAD

**Issue by cyph3rcod3r** [tozny/java-aes-crypto#40]
I am trying to use AES with GCM No padding. I am getting this exception **Caller-provided IV not permitted** in encryption

I am using GCMParamSepc for IV. Can you please help me fix that?

**Comment by SyntaxPolice** [comment]
Thanks! Sounds like you perhaps modified our library to use GCM instead of default AES mode? GCM works quite differently, so the changes would likely be a bit bigger than just changing the mode.

**Comment by SyntaxPolice** [comment]
Since we haven't heard a reply in a few years, I'll go ahead & close this. Eventually, we'd like to provide a version that just supports GCM.
