### ISSUE TITLE
Users be warned.  SHA 256 instead of PBKDF2

### ISSUE THREAD

**Issue by JohnSolstice** [tozny/java-aes-crypto#47]
The key derivation function in the library is SHA 256.  SHA 256 is fast, so deriving the key will be easier than if this library used PBKDF2.  This means the encrypted data is extra vulnerable if you have a weak password.

**Comment by JohnSolstice** [comment]
whoops, meant to type this somewhere else... Too many windows open :man_shrugging:

**Comment by SyntaxPolice** [comment]
Just to be clear, this library DOES use a proper password-based key derivation function.  Thanks for correcting the report :)
