### ISSUE TITLE
Decryption returning something weird.

### ISSUE THREAD

**Issue by joshuasbee** [tozny/java-aes-crypto#49]
[Encrypt.zip](https://github.com/tozny/java-aes-crypto/files/4299932/Encrypt.zip)

The code attached does not decrypt properly, I am unsure why.

**Comment by SyntaxPolice** [comment]
Hi, thanks for using our little library.

I can't quite understand your code flow honestly. I see class local
variables like "hashPassword" getting set at construct time, then a
different password set as a class variable in MainActivity, salt getting
set dynamically on the call to ncrypt and dcrypt counting on that getting
called first with the same object.

Best I can say is that if you send the same ciphertext, password, and salt
to our decrypt function that you used for encrypt, you will get the plain
text out. First step is to debug and ensure that it's the same values.

thanks,

  Isaac

**Comment by joshuasbee** [comment]
You are right, I did a log message from main activity of the ciphertext, and it says it is a null pointer exception. I am passing something in the wrong way.

**Comment by SyntaxPolice** [comment]
Thanks. Glad to help.

>
