### ISSUE TITLE
is IV included into the cipher?

### ISSUE THREAD

**Issue by romanman** [tozny/java-aes-crypto#5]
Hey Guys, Thanks for doing 
that important work. I am 
curious are you also including
the IV inside the final cipher
or you pass it some other way ? 

Thanks in advance.
Roman

**Comment by swenson** [comment]
When encrypting, you get back a `CipherTextIvMac` object, which includes the IV:

https://github.com/tozny/java-aes-crypto/blob/master/AesCbcWithIntegrity.java#L477

**Comment by romanman** [comment]
Yeah but I am not sure how you actually send it on the wire: 
in go lang I see they are doing this tuple ([Ephemeral Key] [IV] [Cipher] [HMAC]  )
are you doing something similar ?

**Comment by swenson** [comment]
Yes. If you look in the toString method, you can see we concatenate the IV,
MAC, and ciphertext.

**Comment by romanman** [comment]
Cool, thanks.
